steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'europe-west1-docker.pkg.dev/cw-patrick-sandbox/ci-cd-test/fastapi:latest', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'europe-west1-docker.pkg.dev/cw-patrick-sandbox/ci-cd-test/fastapi:latest']
  
  - 
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'my-fastapi', '--image', 'europe-west1-docker.pkg.dev/cw-patrick-sandbox/ci-cd-test/fastapi:latest', '--region', 'europe-west1', '--allow-unauthenticated', '--port', '80']
  
  #terraform init

  - id: 'terraform init'
    name: 'hashicorp/terraform:latest'
    script: terraform -chdir="./terraform" init
  
  #terraform plan
  - id: 'terraform plan'
    name: 'hashicorp/terraform:latest'
    script: terraform -chdir="./terraform" plan
   

  #terraform apply
  - id: 'terraform apply'
    name: 'hashicorp/terraform:latest'
    script: terraform -chdir="./terraform" apply -auto-approve
  
  
 